# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 07:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_dogsimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dogs',
        ),
    ]
