# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 17:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CardGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CardMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.IntegerField(null=0)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.CardGroup')),
            ],
        ),
        migrations.CreateModel(
            name='CardRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('matched_date', models.DateTimeField(blank=True, null=True)),
                ('matched_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='want_card', to='cards.Card')),
                ('requested_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='have_card', to='cards.Card')),
                ('requester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.CardGroup')),
            ],
        ),
        migrations.CreateModel(
            name='CardVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.CardGroup')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.CardGroup'),
        ),
        migrations.AddField(
            model_name='card',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.CardMember'),
        ),
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.CardType'),
        ),
        migrations.AddField(
            model_name='card',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.CardVersion'),
        ),
    ]
