# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 07:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardrequest',
            old_name='requested_card',
            new_name='have_card',
        ),
        migrations.RemoveField(
            model_name='cardrequest',
            name='matched_card',
        ),
        migrations.RemoveField(
            model_name='cardrequest',
            name='requester_id',
        ),
        migrations.AddField(
            model_name='cardrequest',
            name='matcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matched_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cardrequest',
            name='requester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='request_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardrequest',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cardrequest',
            name='want_card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='want_card', to='cards.Card'),
            preserve_default=False,
        ),
    ]
